spring.application.name=fraud-detection-backend
server.port=9090

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://ashmithabhuvaneshwaran07_db_user:JF5IIYwrhBmEvzMd@another.gparzjy.mongodb.net/fraud_detection?retryWrites=true&w=majority

# ML Service
ml.service.url=http://localhost:5000

# JWT
jwt.secret=FraudDetectionSuperSecretKey2024XYZABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
jwt.expiration=86400000

# Logging
logging.level.com.fraud=DEBUG
logging.level.org.springframework.security=WARN

# Jackson - handle LocalDateTime
spring.jackson.serialization.write-dates-as-timestamps=false
